### ISSUE TITLE
User settings (saved cross session)

### ISSUE THREAD

**Issue by bcu8** [bradd07/Controller#27] opened 2024-01-24 20:33 UTC
Reconnect (true means ddm will auto start handshake when csim disconnects)
num auto saved files (determines how many auto saved files will be kept before overwrites occur)
connection settings (baud rate, parity, etc.)
handshake timeout? (stops handshake if connection doesnt occur within a set number of seconds)

**Comment by bradd07** [comment] 2024-02-06 00:50
duplicate of #16

**Closed by bradd07** 2024-02-06 00:50 UTC
